spring:
  kafka:
    consumer:
      bootstrap-servers: 127.0.0.1:9092
      key-deserializer: org.apache.kafka.common.serialization.IntegerDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: payment-events-listener-group-mongo
  data:
    mongodb:
      uri: mongodb+srv://admin:admin@payments-cluster.yzpue.mongodb.net/kafka-payments?retryWrites=true&w=majority
      database: kafka-payments
server:
  port: 8081
